# Generated by Django 4.2 on 2023-05-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_status',
            field=models.BooleanField(default=False),
        ),
    ]
