# Generated by Django 4.2.1 on 2023-05-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pic/')),
                ('product_model', models.CharField(max_length=100)),
                ('product_ram', models.CharField(max_length=100)),
            ],
        ),
    ]
