# Generated by Django 4.2.1 on 2023-05-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Product_mst',
            },
        ),
        migrations.CreateModel(
            name='Product_Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='profile_pic/')),
                ('product_model', models.CharField(max_length=100)),
                ('product_ram', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.admin')),
            ],
            options={
                'db_table': 'Product_sub_cat',
            },
        ),
    ]
