# Generated by Django 4.2.1 on 2023-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='product_image',
            field=models.ImageField(upload_to='product_image/'),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='product_mst',
        ),
    ]
